### ISSUE TITLE
Inconsistent number encryption

### ISSUE THREAD

**Issue by abionics** [cyrildever/feistel-py#2]
In this sample number `1403` became `3451` after encryption and decryption

```python
from feistel import FPECipher, SHA_256

cipher = FPECipher(SHA_256, "some-32-byte-long-key-to-be-safe", 128)

number = 1403
obfuscated = cipher.encrypt_number(number)
deciphered = cipher.decrypt_number(obfuscated)
print(number, deciphered)
>>> 1403 3451
```

**Comment by cyrildever** [comment]
Sorry but I can't reproduce. I used the same number (`1403`) and got the identical result once deciphered, the obfuscated number being `3872`. 
By the way, there is no `encrypt_number()` or `decrypt_number()` methods on `FPECipher` but `encryptNumber()` and `decryptNumber()`.

**Comment by abionics** [comment]
@cyrildever check this code in any online IDE
For example https://hub.ovh2.mybinder.org/user/abionics-1b3eda-db13d776858e7f3-kc8ps56l/lab/tree/sample.ipynb

**Comment by cyrildever** [comment]
I'm not able to reach your notebook on MyBinder. I receive a 424 error.

**Comment by cyrildever** [comment]
Sorry again, I did my test in the TypeScript version, not the Python one. I check and get back to you.

**Comment by cyrildever** [comment]
You're right: we've got a pb here. I will not have time to address it before the week-end but it's on me.

**Comment by cyrildever** [comment]
That was actually a simple one, and I couldn't resist fixing it.

BTW, that's also why the Python version is still in version `v0.~`: I haven't had time to test it thoroughly enough. So thanks for the issue.

**Comment by abionics** [comment]
Thank you!
